# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: hecktor_datamodule.yaml # choose the datamodule for evaluation
  - model: hecktor_model.yaml
  - callbacks: default.yaml
  - logger: wandb
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir:  ${original_work_dir}/data


print_config: True

ignore_warnings: True

seed: 786

name: "default"

# passing checkpoint path is necessary
ckpt_path: "logs/experiments/runs/default/2022-05-11_20-35-35/checkpoints/epoch_043.ckpt"
